# https://openapi-generator.tech/docs/usage/#generate
apiPackage: Api
gitRepoId: dhl-gspl
gitUserId: spysystem
invokerPackage: DHL\GSPL
modelPackage: Model
composerVendorName: spysystem
composerProjectName: dhl-gspl
