<?php
/**
 * AddressModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Global Service Point Locator API
 *
 * Web service for getting DHL Service Points
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DHL\GSPL\Model;

/**
 * AddressModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddressModelAttributes
{
    public string $strAddressLine1 = 'address_line1';
    public string $strCity = 'city';
    public string $strZipCode = 'zip_code';
    public string $strCountry = 'country';
    public string $strCountryDivisionCode = 'country_division_code';
    public string $strCountryDivisionCodeType = 'country_division_code_type';
    public string $strHtml = 'html';
}

