<?php
/**
 * Map
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Global Service Point Locator API
 *
 * Web service for getting DHL Service Points
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DHL\GSPL\Model;

use \ArrayAccess;
use \DHL\GSPL\ObjectSerializer;

/**
 * Map Class Doc Comment
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Map implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * Return an object with the Model Fields
      *
      * @return MapModelFields
      */
    public static function GetModelFields(): MapModelFields
    {
        return new MapModelFields();
    }

    /**
      * Return an object with the Model Attributes
      *
      * @return MapModelAttributes
      */
    public static function GetModelAttributes(): MapModelAttributes
    {
        return new MapModelAttributes();
    }

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Map';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'sp_detail' => 'string',
        'aditional_info' => 'string',
        'services' => 'string',
        'opening_hours' => 'string',
        'limitation_by_shipment' => 'string',
        'holiday_hours' => 'string',
        'limitation' => 'string',
        'limitation_by_piece' => 'string',
        'print' => 'string',
        'details' => 'string',
        'route' => 'string',
        'contact_details' => 'string',
        'found' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'sp_detail' => null,
        'aditional_info' => null,
        'services' => null,
        'opening_hours' => null,
        'limitation_by_shipment' => null,
        'holiday_hours' => null,
        'limitation' => null,
        'limitation_by_piece' => null,
        'print' => null,
        'details' => null,
        'route' => null,
        'contact_details' => null,
        'found' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'sp_detail' => false,
		'aditional_info' => false,
		'services' => false,
		'opening_hours' => false,
		'limitation_by_shipment' => false,
		'holiday_hours' => false,
		'limitation' => false,
		'limitation_by_piece' => false,
		'print' => false,
		'details' => false,
		'route' => false,
		'contact_details' => false,
		'found' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sp_detail' => 'spDetail',
        'aditional_info' => 'aditionalInfo',
        'services' => 'services',
        'opening_hours' => 'openingHours',
        'limitation_by_shipment' => 'limitationByShipment',
        'holiday_hours' => 'holidayHours',
        'limitation' => 'limitation',
        'limitation_by_piece' => 'limitationByPiece',
        'print' => 'print',
        'details' => 'details',
        'route' => 'route',
        'contact_details' => 'contactDetails',
        'found' => 'found'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sp_detail' => 'setSpDetail',
        'aditional_info' => 'setAditionalInfo',
        'services' => 'setServices',
        'opening_hours' => 'setOpeningHours',
        'limitation_by_shipment' => 'setLimitationByShipment',
        'holiday_hours' => 'setHolidayHours',
        'limitation' => 'setLimitation',
        'limitation_by_piece' => 'setLimitationByPiece',
        'print' => 'setPrint',
        'details' => 'setDetails',
        'route' => 'setRoute',
        'contact_details' => 'setContactDetails',
        'found' => 'setFound'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sp_detail' => 'getSpDetail',
        'aditional_info' => 'getAditionalInfo',
        'services' => 'getServices',
        'opening_hours' => 'getOpeningHours',
        'limitation_by_shipment' => 'getLimitationByShipment',
        'holiday_hours' => 'getHolidayHours',
        'limitation' => 'getLimitation',
        'limitation_by_piece' => 'getLimitationByPiece',
        'print' => 'getPrint',
        'details' => 'getDetails',
        'route' => 'getRoute',
        'contact_details' => 'getContactDetails',
        'found' => 'getFound'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('sp_detail', $data ?? [], null);
        $this->setIfExists('aditional_info', $data ?? [], null);
        $this->setIfExists('services', $data ?? [], null);
        $this->setIfExists('opening_hours', $data ?? [], null);
        $this->setIfExists('limitation_by_shipment', $data ?? [], null);
        $this->setIfExists('holiday_hours', $data ?? [], null);
        $this->setIfExists('limitation', $data ?? [], null);
        $this->setIfExists('limitation_by_piece', $data ?? [], null);
        $this->setIfExists('print', $data ?? [], null);
        $this->setIfExists('details', $data ?? [], null);
        $this->setIfExists('route', $data ?? [], null);
        $this->setIfExists('contact_details', $data ?? [], null);
        $this->setIfExists('found', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sp_detail
     *
     * @return string|null
     */
    public function getSpDetail()
    {
        return $this->container['sp_detail'];
    }

    /**
     * Sets sp_detail
     *
     * @param string|null $sp_detail sp_detail
     *
     * @return self
     */
    public function setSpDetail($sp_detail)
    {

        if (is_null($sp_detail)) {
            throw new \InvalidArgumentException('non-nullable sp_detail cannot be null');
        }

        $this->container['sp_detail'] = $sp_detail;

        return $this;
    }

    /**
     * Gets aditional_info
     *
     * @return string|null
     */
    public function getAditionalInfo()
    {
        return $this->container['aditional_info'];
    }

    /**
     * Sets aditional_info
     *
     * @param string|null $aditional_info aditional_info
     *
     * @return self
     */
    public function setAditionalInfo($aditional_info)
    {

        if (is_null($aditional_info)) {
            throw new \InvalidArgumentException('non-nullable aditional_info cannot be null');
        }

        $this->container['aditional_info'] = $aditional_info;

        return $this;
    }

    /**
     * Gets services
     *
     * @return string|null
     */
    public function getServices()
    {
        return $this->container['services'];
    }

    /**
     * Sets services
     *
     * @param string|null $services services
     *
     * @return self
     */
    public function setServices($services)
    {

        if (is_null($services)) {
            throw new \InvalidArgumentException('non-nullable services cannot be null');
        }

        $this->container['services'] = $services;

        return $this;
    }

    /**
     * Gets opening_hours
     *
     * @return string|null
     */
    public function getOpeningHours()
    {
        return $this->container['opening_hours'];
    }

    /**
     * Sets opening_hours
     *
     * @param string|null $opening_hours opening_hours
     *
     * @return self
     */
    public function setOpeningHours($opening_hours)
    {

        if (is_null($opening_hours)) {
            throw new \InvalidArgumentException('non-nullable opening_hours cannot be null');
        }

        $this->container['opening_hours'] = $opening_hours;

        return $this;
    }

    /**
     * Gets limitation_by_shipment
     *
     * @return string|null
     */
    public function getLimitationByShipment()
    {
        return $this->container['limitation_by_shipment'];
    }

    /**
     * Sets limitation_by_shipment
     *
     * @param string|null $limitation_by_shipment limitation_by_shipment
     *
     * @return self
     */
    public function setLimitationByShipment($limitation_by_shipment)
    {

        if (is_null($limitation_by_shipment)) {
            throw new \InvalidArgumentException('non-nullable limitation_by_shipment cannot be null');
        }

        $this->container['limitation_by_shipment'] = $limitation_by_shipment;

        return $this;
    }

    /**
     * Gets holiday_hours
     *
     * @return string|null
     */
    public function getHolidayHours()
    {
        return $this->container['holiday_hours'];
    }

    /**
     * Sets holiday_hours
     *
     * @param string|null $holiday_hours holiday_hours
     *
     * @return self
     */
    public function setHolidayHours($holiday_hours)
    {

        if (is_null($holiday_hours)) {
            throw new \InvalidArgumentException('non-nullable holiday_hours cannot be null');
        }

        $this->container['holiday_hours'] = $holiday_hours;

        return $this;
    }

    /**
     * Gets limitation
     *
     * @return string|null
     */
    public function getLimitation()
    {
        return $this->container['limitation'];
    }

    /**
     * Sets limitation
     *
     * @param string|null $limitation limitation
     *
     * @return self
     */
    public function setLimitation($limitation)
    {

        if (is_null($limitation)) {
            throw new \InvalidArgumentException('non-nullable limitation cannot be null');
        }

        $this->container['limitation'] = $limitation;

        return $this;
    }

    /**
     * Gets limitation_by_piece
     *
     * @return string|null
     */
    public function getLimitationByPiece()
    {
        return $this->container['limitation_by_piece'];
    }

    /**
     * Sets limitation_by_piece
     *
     * @param string|null $limitation_by_piece limitation_by_piece
     *
     * @return self
     */
    public function setLimitationByPiece($limitation_by_piece)
    {

        if (is_null($limitation_by_piece)) {
            throw new \InvalidArgumentException('non-nullable limitation_by_piece cannot be null');
        }

        $this->container['limitation_by_piece'] = $limitation_by_piece;

        return $this;
    }

    /**
     * Gets print
     *
     * @return string|null
     */
    public function getPrint()
    {
        return $this->container['print'];
    }

    /**
     * Sets print
     *
     * @param string|null $print print
     *
     * @return self
     */
    public function setPrint($print)
    {

        if (is_null($print)) {
            throw new \InvalidArgumentException('non-nullable print cannot be null');
        }

        $this->container['print'] = $print;

        return $this;
    }

    /**
     * Gets details
     *
     * @return string|null
     */
    public function getDetails()
    {
        return $this->container['details'];
    }

    /**
     * Sets details
     *
     * @param string|null $details details
     *
     * @return self
     */
    public function setDetails($details)
    {

        if (is_null($details)) {
            throw new \InvalidArgumentException('non-nullable details cannot be null');
        }

        $this->container['details'] = $details;

        return $this;
    }

    /**
     * Gets route
     *
     * @return string|null
     */
    public function getRoute()
    {
        return $this->container['route'];
    }

    /**
     * Sets route
     *
     * @param string|null $route route
     *
     * @return self
     */
    public function setRoute($route)
    {

        if (is_null($route)) {
            throw new \InvalidArgumentException('non-nullable route cannot be null');
        }

        $this->container['route'] = $route;

        return $this;
    }

    /**
     * Gets contact_details
     *
     * @return string|null
     */
    public function getContactDetails()
    {
        return $this->container['contact_details'];
    }

    /**
     * Sets contact_details
     *
     * @param string|null $contact_details contact_details
     *
     * @return self
     */
    public function setContactDetails($contact_details)
    {

        if (is_null($contact_details)) {
            throw new \InvalidArgumentException('non-nullable contact_details cannot be null');
        }

        $this->container['contact_details'] = $contact_details;

        return $this;
    }

    /**
     * Gets found
     *
     * @return string|null
     */
    public function getFound()
    {
        return $this->container['found'];
    }

    /**
     * Sets found
     *
     * @param string|null $found found
     *
     * @return self
     */
    public function setFound($found)
    {

        if (is_null($found)) {
            throw new \InvalidArgumentException('non-nullable found cannot be null');
        }

        $this->container['found'] = $found;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return (string)json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


