<?php
/**
 * MapModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Global Service Point Locator API
 *
 * Web service for getting DHL Service Points
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DHL\GSPL\Model;

/**
 * MapModelFields Class Doc Comment
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MapModelFields
{
    public string $strSpDetail = 'spDetail';
    public string $strAditionalInfo = 'aditionalInfo';
    public string $strServices = 'services';
    public string $strOpeningHours = 'openingHours';
    public string $strLimitationByShipment = 'limitationByShipment';
    public string $strHolidayHours = 'holidayHours';
    public string $strLimitation = 'limitation';
    public string $strLimitationByPiece = 'limitationByPiece';
    public string $strPrint = 'print';
    public string $strDetails = 'details';
    public string $strRoute = 'route';
    public string $strContactDetails = 'contactDetails';
    public string $strFound = 'found';
}

