<?php
/**
 * ServicePointModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Global Service Point Locator API
 *
 * Web service for getting DHL Service Points
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DHL\GSPL\Model;

/**
 * ServicePointModelFields Class Doc Comment
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServicePointModelFields
{
    public string $strFacilityId = 'facilityId';
    public string $strFacilityTypeCode = 'facilityTypeCode';
    public string $strServiceAreaCode = 'serviceAreaCode';
    public string $strServicePointName = 'servicePointName';
    public string $strServicePointNameFormatted = 'servicePointNameFormatted';
    public string $strLocalName = 'localName';
    public string $strServicePointType = 'servicePointType';
    public string $strAddress = 'address';
    public string $strGeoLocation = 'geoLocation';
    public string $strDistance = 'distance';
    public string $strOpeningHours = 'openingHours';
    public string $strServicePointCapabilities = 'servicePointCapabilities';
    public string $strContactDetails = 'contactDetails';
    public string $strShippingCutOffTimeHtml = 'shippingCutOffTimeHtml';
    public string $strDistanceValue = 'distanceValue';
    public string $strDistanceMetric = 'distanceMetric';
    public string $strLanguage = 'language';
    public string $strShipmentLimitations = 'shipmentLimitations';
    public string $strShipmentLimitationsByPiece = 'shipmentLimitationsByPiece';
    public string $strChargeCode = 'chargeCode';
}

