<?php
/**
 * ServicePointCapabilities
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Global Service Point Locator API
 *
 * Web service for getting DHL Service Points
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DHL\GSPL\Model;

use \ArrayAccess;
use \DHL\GSPL\ObjectSerializer;

/**
 * ServicePointCapabilities Class Doc Comment
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ServicePointCapabilities implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * Return an object with the Model Fields
      *
      * @return ServicePointCapabilitiesModelFields
      */
    public static function GetModelFields(): ServicePointCapabilitiesModelFields
    {
        return new ServicePointCapabilitiesModelFields();
    }

    /**
      * Return an object with the Model Attributes
      *
      * @return ServicePointCapabilitiesModelAttributes
      */
    public static function GetModelAttributes(): ServicePointCapabilitiesModelAttributes
    {
        return new ServicePointCapabilitiesModelAttributes();
    }

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ServicePointCapabilities';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'parking_available' => 'bool',
        'disabled_access' => 'bool',
        'shipment_drop_off' => 'bool',
        'shipment_collection' => 'bool',
        'international_shipping' => 'bool',
        'domestic_shipping' => 'bool',
        'account_shippers' => 'bool',
        'label_printing' => 'bool',
        'insurance' => 'bool',
        'import_charges' => 'bool',
        'packaging' => 'bool',
        'receiver_paid' => 'bool',
        'visa_program' => 'bool',
        'pay_with_cash' => 'bool',
        'pay_with_credit_card' => 'bool',
        'pay_with_cheque' => 'bool',
        'pay_with_mobile' => 'bool',
        'pay_with_pay_pal' => 'bool',
        'parkint_title' => 'string',
        'disabled_access_title' => 'string',
        'piece_weight_limit' => 'int',
        'piece_weight_limit_unit' => 'string',
        'piece_dimensions_limit' => '\DHL\GSPL\Model\Dimensions',
        'piece_dimensions_limit_unit' => 'string',
        'piece_count_limit' => 'int',
        'html' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'parking_available' => null,
        'disabled_access' => null,
        'shipment_drop_off' => null,
        'shipment_collection' => null,
        'international_shipping' => null,
        'domestic_shipping' => null,
        'account_shippers' => null,
        'label_printing' => null,
        'insurance' => null,
        'import_charges' => null,
        'packaging' => null,
        'receiver_paid' => null,
        'visa_program' => null,
        'pay_with_cash' => null,
        'pay_with_credit_card' => null,
        'pay_with_cheque' => null,
        'pay_with_mobile' => null,
        'pay_with_pay_pal' => null,
        'parkint_title' => null,
        'disabled_access_title' => null,
        'piece_weight_limit' => null,
        'piece_weight_limit_unit' => null,
        'piece_dimensions_limit' => null,
        'piece_dimensions_limit_unit' => null,
        'piece_count_limit' => null,
        'html' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'parking_available' => false,
		'disabled_access' => false,
		'shipment_drop_off' => false,
		'shipment_collection' => false,
		'international_shipping' => false,
		'domestic_shipping' => false,
		'account_shippers' => false,
		'label_printing' => false,
		'insurance' => false,
		'import_charges' => false,
		'packaging' => false,
		'receiver_paid' => false,
		'visa_program' => false,
		'pay_with_cash' => false,
		'pay_with_credit_card' => false,
		'pay_with_cheque' => false,
		'pay_with_mobile' => false,
		'pay_with_pay_pal' => false,
		'parkint_title' => false,
		'disabled_access_title' => false,
		'piece_weight_limit' => false,
		'piece_weight_limit_unit' => false,
		'piece_dimensions_limit' => false,
		'piece_dimensions_limit_unit' => false,
		'piece_count_limit' => false,
		'html' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'parking_available' => 'parkingAvailable',
        'disabled_access' => 'disabledAccess',
        'shipment_drop_off' => 'shipmentDropOff',
        'shipment_collection' => 'shipmentCollection',
        'international_shipping' => 'internationalShipping',
        'domestic_shipping' => 'domesticShipping',
        'account_shippers' => 'accountShippers',
        'label_printing' => 'labelPrinting',
        'insurance' => 'insurance',
        'import_charges' => 'importCharges',
        'packaging' => 'packaging',
        'receiver_paid' => 'receiverPaid',
        'visa_program' => 'visaProgram',
        'pay_with_cash' => 'payWithCash',
        'pay_with_credit_card' => 'payWithCreditCard',
        'pay_with_cheque' => 'payWithCheque',
        'pay_with_mobile' => 'payWithMobile',
        'pay_with_pay_pal' => 'payWithPayPal',
        'parkint_title' => 'parkintTitle',
        'disabled_access_title' => 'disabledAccessTitle',
        'piece_weight_limit' => 'pieceWeightLimit',
        'piece_weight_limit_unit' => 'pieceWeightLimitUnit',
        'piece_dimensions_limit' => 'pieceDimensionsLimit',
        'piece_dimensions_limit_unit' => 'pieceDimensionsLimitUnit',
        'piece_count_limit' => 'pieceCountLimit',
        'html' => 'html'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'parking_available' => 'setParkingAvailable',
        'disabled_access' => 'setDisabledAccess',
        'shipment_drop_off' => 'setShipmentDropOff',
        'shipment_collection' => 'setShipmentCollection',
        'international_shipping' => 'setInternationalShipping',
        'domestic_shipping' => 'setDomesticShipping',
        'account_shippers' => 'setAccountShippers',
        'label_printing' => 'setLabelPrinting',
        'insurance' => 'setInsurance',
        'import_charges' => 'setImportCharges',
        'packaging' => 'setPackaging',
        'receiver_paid' => 'setReceiverPaid',
        'visa_program' => 'setVisaProgram',
        'pay_with_cash' => 'setPayWithCash',
        'pay_with_credit_card' => 'setPayWithCreditCard',
        'pay_with_cheque' => 'setPayWithCheque',
        'pay_with_mobile' => 'setPayWithMobile',
        'pay_with_pay_pal' => 'setPayWithPayPal',
        'parkint_title' => 'setParkintTitle',
        'disabled_access_title' => 'setDisabledAccessTitle',
        'piece_weight_limit' => 'setPieceWeightLimit',
        'piece_weight_limit_unit' => 'setPieceWeightLimitUnit',
        'piece_dimensions_limit' => 'setPieceDimensionsLimit',
        'piece_dimensions_limit_unit' => 'setPieceDimensionsLimitUnit',
        'piece_count_limit' => 'setPieceCountLimit',
        'html' => 'setHtml'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'parking_available' => 'getParkingAvailable',
        'disabled_access' => 'getDisabledAccess',
        'shipment_drop_off' => 'getShipmentDropOff',
        'shipment_collection' => 'getShipmentCollection',
        'international_shipping' => 'getInternationalShipping',
        'domestic_shipping' => 'getDomesticShipping',
        'account_shippers' => 'getAccountShippers',
        'label_printing' => 'getLabelPrinting',
        'insurance' => 'getInsurance',
        'import_charges' => 'getImportCharges',
        'packaging' => 'getPackaging',
        'receiver_paid' => 'getReceiverPaid',
        'visa_program' => 'getVisaProgram',
        'pay_with_cash' => 'getPayWithCash',
        'pay_with_credit_card' => 'getPayWithCreditCard',
        'pay_with_cheque' => 'getPayWithCheque',
        'pay_with_mobile' => 'getPayWithMobile',
        'pay_with_pay_pal' => 'getPayWithPayPal',
        'parkint_title' => 'getParkintTitle',
        'disabled_access_title' => 'getDisabledAccessTitle',
        'piece_weight_limit' => 'getPieceWeightLimit',
        'piece_weight_limit_unit' => 'getPieceWeightLimitUnit',
        'piece_dimensions_limit' => 'getPieceDimensionsLimit',
        'piece_dimensions_limit_unit' => 'getPieceDimensionsLimitUnit',
        'piece_count_limit' => 'getPieceCountLimit',
        'html' => 'getHtml'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('parking_available', $data ?? [], null);
        $this->setIfExists('disabled_access', $data ?? [], null);
        $this->setIfExists('shipment_drop_off', $data ?? [], null);
        $this->setIfExists('shipment_collection', $data ?? [], null);
        $this->setIfExists('international_shipping', $data ?? [], null);
        $this->setIfExists('domestic_shipping', $data ?? [], null);
        $this->setIfExists('account_shippers', $data ?? [], null);
        $this->setIfExists('label_printing', $data ?? [], null);
        $this->setIfExists('insurance', $data ?? [], null);
        $this->setIfExists('import_charges', $data ?? [], null);
        $this->setIfExists('packaging', $data ?? [], null);
        $this->setIfExists('receiver_paid', $data ?? [], null);
        $this->setIfExists('visa_program', $data ?? [], null);
        $this->setIfExists('pay_with_cash', $data ?? [], null);
        $this->setIfExists('pay_with_credit_card', $data ?? [], null);
        $this->setIfExists('pay_with_cheque', $data ?? [], null);
        $this->setIfExists('pay_with_mobile', $data ?? [], null);
        $this->setIfExists('pay_with_pay_pal', $data ?? [], null);
        $this->setIfExists('parkint_title', $data ?? [], null);
        $this->setIfExists('disabled_access_title', $data ?? [], null);
        $this->setIfExists('piece_weight_limit', $data ?? [], null);
        $this->setIfExists('piece_weight_limit_unit', $data ?? [], null);
        $this->setIfExists('piece_dimensions_limit', $data ?? [], null);
        $this->setIfExists('piece_dimensions_limit_unit', $data ?? [], null);
        $this->setIfExists('piece_count_limit', $data ?? [], null);
        $this->setIfExists('html', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets parking_available
     *
     * @return bool|null
     */
    public function getParkingAvailable()
    {
        return $this->container['parking_available'];
    }

    /**
     * Sets parking_available
     *
     * @param bool|null $parking_available parking_available
     *
     * @return self
     */
    public function setParkingAvailable($parking_available)
    {

        if (is_null($parking_available)) {
            throw new \InvalidArgumentException('non-nullable parking_available cannot be null');
        }

        $this->container['parking_available'] = $parking_available;

        return $this;
    }

    /**
     * Gets disabled_access
     *
     * @return bool|null
     */
    public function getDisabledAccess()
    {
        return $this->container['disabled_access'];
    }

    /**
     * Sets disabled_access
     *
     * @param bool|null $disabled_access disabled_access
     *
     * @return self
     */
    public function setDisabledAccess($disabled_access)
    {

        if (is_null($disabled_access)) {
            throw new \InvalidArgumentException('non-nullable disabled_access cannot be null');
        }

        $this->container['disabled_access'] = $disabled_access;

        return $this;
    }

    /**
     * Gets shipment_drop_off
     *
     * @return bool|null
     */
    public function getShipmentDropOff()
    {
        return $this->container['shipment_drop_off'];
    }

    /**
     * Sets shipment_drop_off
     *
     * @param bool|null $shipment_drop_off shipment_drop_off
     *
     * @return self
     */
    public function setShipmentDropOff($shipment_drop_off)
    {

        if (is_null($shipment_drop_off)) {
            throw new \InvalidArgumentException('non-nullable shipment_drop_off cannot be null');
        }

        $this->container['shipment_drop_off'] = $shipment_drop_off;

        return $this;
    }

    /**
     * Gets shipment_collection
     *
     * @return bool|null
     */
    public function getShipmentCollection()
    {
        return $this->container['shipment_collection'];
    }

    /**
     * Sets shipment_collection
     *
     * @param bool|null $shipment_collection shipment_collection
     *
     * @return self
     */
    public function setShipmentCollection($shipment_collection)
    {

        if (is_null($shipment_collection)) {
            throw new \InvalidArgumentException('non-nullable shipment_collection cannot be null');
        }

        $this->container['shipment_collection'] = $shipment_collection;

        return $this;
    }

    /**
     * Gets international_shipping
     *
     * @return bool|null
     */
    public function getInternationalShipping()
    {
        return $this->container['international_shipping'];
    }

    /**
     * Sets international_shipping
     *
     * @param bool|null $international_shipping international_shipping
     *
     * @return self
     */
    public function setInternationalShipping($international_shipping)
    {

        if (is_null($international_shipping)) {
            throw new \InvalidArgumentException('non-nullable international_shipping cannot be null');
        }

        $this->container['international_shipping'] = $international_shipping;

        return $this;
    }

    /**
     * Gets domestic_shipping
     *
     * @return bool|null
     */
    public function getDomesticShipping()
    {
        return $this->container['domestic_shipping'];
    }

    /**
     * Sets domestic_shipping
     *
     * @param bool|null $domestic_shipping domestic_shipping
     *
     * @return self
     */
    public function setDomesticShipping($domestic_shipping)
    {

        if (is_null($domestic_shipping)) {
            throw new \InvalidArgumentException('non-nullable domestic_shipping cannot be null');
        }

        $this->container['domestic_shipping'] = $domestic_shipping;

        return $this;
    }

    /**
     * Gets account_shippers
     *
     * @return bool|null
     */
    public function getAccountShippers()
    {
        return $this->container['account_shippers'];
    }

    /**
     * Sets account_shippers
     *
     * @param bool|null $account_shippers account_shippers
     *
     * @return self
     */
    public function setAccountShippers($account_shippers)
    {

        if (is_null($account_shippers)) {
            throw new \InvalidArgumentException('non-nullable account_shippers cannot be null');
        }

        $this->container['account_shippers'] = $account_shippers;

        return $this;
    }

    /**
     * Gets label_printing
     *
     * @return bool|null
     */
    public function getLabelPrinting()
    {
        return $this->container['label_printing'];
    }

    /**
     * Sets label_printing
     *
     * @param bool|null $label_printing label_printing
     *
     * @return self
     */
    public function setLabelPrinting($label_printing)
    {

        if (is_null($label_printing)) {
            throw new \InvalidArgumentException('non-nullable label_printing cannot be null');
        }

        $this->container['label_printing'] = $label_printing;

        return $this;
    }

    /**
     * Gets insurance
     *
     * @return bool|null
     */
    public function getInsurance()
    {
        return $this->container['insurance'];
    }

    /**
     * Sets insurance
     *
     * @param bool|null $insurance insurance
     *
     * @return self
     */
    public function setInsurance($insurance)
    {

        if (is_null($insurance)) {
            throw new \InvalidArgumentException('non-nullable insurance cannot be null');
        }

        $this->container['insurance'] = $insurance;

        return $this;
    }

    /**
     * Gets import_charges
     *
     * @return bool|null
     */
    public function getImportCharges()
    {
        return $this->container['import_charges'];
    }

    /**
     * Sets import_charges
     *
     * @param bool|null $import_charges import_charges
     *
     * @return self
     */
    public function setImportCharges($import_charges)
    {

        if (is_null($import_charges)) {
            throw new \InvalidArgumentException('non-nullable import_charges cannot be null');
        }

        $this->container['import_charges'] = $import_charges;

        return $this;
    }

    /**
     * Gets packaging
     *
     * @return bool|null
     */
    public function getPackaging()
    {
        return $this->container['packaging'];
    }

    /**
     * Sets packaging
     *
     * @param bool|null $packaging packaging
     *
     * @return self
     */
    public function setPackaging($packaging)
    {

        if (is_null($packaging)) {
            throw new \InvalidArgumentException('non-nullable packaging cannot be null');
        }

        $this->container['packaging'] = $packaging;

        return $this;
    }

    /**
     * Gets receiver_paid
     *
     * @return bool|null
     */
    public function getReceiverPaid()
    {
        return $this->container['receiver_paid'];
    }

    /**
     * Sets receiver_paid
     *
     * @param bool|null $receiver_paid receiver_paid
     *
     * @return self
     */
    public function setReceiverPaid($receiver_paid)
    {

        if (is_null($receiver_paid)) {
            throw new \InvalidArgumentException('non-nullable receiver_paid cannot be null');
        }

        $this->container['receiver_paid'] = $receiver_paid;

        return $this;
    }

    /**
     * Gets visa_program
     *
     * @return bool|null
     */
    public function getVisaProgram()
    {
        return $this->container['visa_program'];
    }

    /**
     * Sets visa_program
     *
     * @param bool|null $visa_program visa_program
     *
     * @return self
     */
    public function setVisaProgram($visa_program)
    {

        if (is_null($visa_program)) {
            throw new \InvalidArgumentException('non-nullable visa_program cannot be null');
        }

        $this->container['visa_program'] = $visa_program;

        return $this;
    }

    /**
     * Gets pay_with_cash
     *
     * @return bool|null
     */
    public function getPayWithCash()
    {
        return $this->container['pay_with_cash'];
    }

    /**
     * Sets pay_with_cash
     *
     * @param bool|null $pay_with_cash pay_with_cash
     *
     * @return self
     */
    public function setPayWithCash($pay_with_cash)
    {

        if (is_null($pay_with_cash)) {
            throw new \InvalidArgumentException('non-nullable pay_with_cash cannot be null');
        }

        $this->container['pay_with_cash'] = $pay_with_cash;

        return $this;
    }

    /**
     * Gets pay_with_credit_card
     *
     * @return bool|null
     */
    public function getPayWithCreditCard()
    {
        return $this->container['pay_with_credit_card'];
    }

    /**
     * Sets pay_with_credit_card
     *
     * @param bool|null $pay_with_credit_card pay_with_credit_card
     *
     * @return self
     */
    public function setPayWithCreditCard($pay_with_credit_card)
    {

        if (is_null($pay_with_credit_card)) {
            throw new \InvalidArgumentException('non-nullable pay_with_credit_card cannot be null');
        }

        $this->container['pay_with_credit_card'] = $pay_with_credit_card;

        return $this;
    }

    /**
     * Gets pay_with_cheque
     *
     * @return bool|null
     */
    public function getPayWithCheque()
    {
        return $this->container['pay_with_cheque'];
    }

    /**
     * Sets pay_with_cheque
     *
     * @param bool|null $pay_with_cheque pay_with_cheque
     *
     * @return self
     */
    public function setPayWithCheque($pay_with_cheque)
    {

        if (is_null($pay_with_cheque)) {
            throw new \InvalidArgumentException('non-nullable pay_with_cheque cannot be null');
        }

        $this->container['pay_with_cheque'] = $pay_with_cheque;

        return $this;
    }

    /**
     * Gets pay_with_mobile
     *
     * @return bool|null
     */
    public function getPayWithMobile()
    {
        return $this->container['pay_with_mobile'];
    }

    /**
     * Sets pay_with_mobile
     *
     * @param bool|null $pay_with_mobile pay_with_mobile
     *
     * @return self
     */
    public function setPayWithMobile($pay_with_mobile)
    {

        if (is_null($pay_with_mobile)) {
            throw new \InvalidArgumentException('non-nullable pay_with_mobile cannot be null');
        }

        $this->container['pay_with_mobile'] = $pay_with_mobile;

        return $this;
    }

    /**
     * Gets pay_with_pay_pal
     *
     * @return bool|null
     */
    public function getPayWithPayPal()
    {
        return $this->container['pay_with_pay_pal'];
    }

    /**
     * Sets pay_with_pay_pal
     *
     * @param bool|null $pay_with_pay_pal pay_with_pay_pal
     *
     * @return self
     */
    public function setPayWithPayPal($pay_with_pay_pal)
    {

        if (is_null($pay_with_pay_pal)) {
            throw new \InvalidArgumentException('non-nullable pay_with_pay_pal cannot be null');
        }

        $this->container['pay_with_pay_pal'] = $pay_with_pay_pal;

        return $this;
    }

    /**
     * Gets parkint_title
     *
     * @return string|null
     */
    public function getParkintTitle()
    {
        return $this->container['parkint_title'];
    }

    /**
     * Sets parkint_title
     *
     * @param string|null $parkint_title parkint_title
     *
     * @return self
     */
    public function setParkintTitle($parkint_title)
    {

        if (is_null($parkint_title)) {
            throw new \InvalidArgumentException('non-nullable parkint_title cannot be null');
        }

        $this->container['parkint_title'] = $parkint_title;

        return $this;
    }

    /**
     * Gets disabled_access_title
     *
     * @return string|null
     */
    public function getDisabledAccessTitle()
    {
        return $this->container['disabled_access_title'];
    }

    /**
     * Sets disabled_access_title
     *
     * @param string|null $disabled_access_title disabled_access_title
     *
     * @return self
     */
    public function setDisabledAccessTitle($disabled_access_title)
    {

        if (is_null($disabled_access_title)) {
            throw new \InvalidArgumentException('non-nullable disabled_access_title cannot be null');
        }

        $this->container['disabled_access_title'] = $disabled_access_title;

        return $this;
    }

    /**
     * Gets piece_weight_limit
     *
     * @return int|null
     */
    public function getPieceWeightLimit()
    {
        return $this->container['piece_weight_limit'];
    }

    /**
     * Sets piece_weight_limit
     *
     * @param int|null $piece_weight_limit piece_weight_limit
     *
     * @return self
     */
    public function setPieceWeightLimit($piece_weight_limit)
    {

        if (is_null($piece_weight_limit)) {
            throw new \InvalidArgumentException('non-nullable piece_weight_limit cannot be null');
        }

        $this->container['piece_weight_limit'] = $piece_weight_limit;

        return $this;
    }

    /**
     * Gets piece_weight_limit_unit
     *
     * @return string|null
     */
    public function getPieceWeightLimitUnit()
    {
        return $this->container['piece_weight_limit_unit'];
    }

    /**
     * Sets piece_weight_limit_unit
     *
     * @param string|null $piece_weight_limit_unit piece_weight_limit_unit
     *
     * @return self
     */
    public function setPieceWeightLimitUnit($piece_weight_limit_unit)
    {

        if (is_null($piece_weight_limit_unit)) {
            throw new \InvalidArgumentException('non-nullable piece_weight_limit_unit cannot be null');
        }

        $this->container['piece_weight_limit_unit'] = $piece_weight_limit_unit;

        return $this;
    }

    /**
     * Gets piece_dimensions_limit
     *
     * @return \DHL\GSPL\Model\Dimensions|null
     */
    public function getPieceDimensionsLimit()
    {
        return $this->container['piece_dimensions_limit'];
    }

    /**
     * Sets piece_dimensions_limit
     *
     * @param \DHL\GSPL\Model\Dimensions|null $piece_dimensions_limit piece_dimensions_limit
     *
     * @return self
     */
    public function setPieceDimensionsLimit($piece_dimensions_limit)
    {

        if (is_null($piece_dimensions_limit)) {
            throw new \InvalidArgumentException('non-nullable piece_dimensions_limit cannot be null');
        }

        $this->container['piece_dimensions_limit'] = $piece_dimensions_limit;

        return $this;
    }

    /**
     * Gets piece_dimensions_limit_unit
     *
     * @return string|null
     */
    public function getPieceDimensionsLimitUnit()
    {
        return $this->container['piece_dimensions_limit_unit'];
    }

    /**
     * Sets piece_dimensions_limit_unit
     *
     * @param string|null $piece_dimensions_limit_unit piece_dimensions_limit_unit
     *
     * @return self
     */
    public function setPieceDimensionsLimitUnit($piece_dimensions_limit_unit)
    {

        if (is_null($piece_dimensions_limit_unit)) {
            throw new \InvalidArgumentException('non-nullable piece_dimensions_limit_unit cannot be null');
        }

        $this->container['piece_dimensions_limit_unit'] = $piece_dimensions_limit_unit;

        return $this;
    }

    /**
     * Gets piece_count_limit
     *
     * @return int|null
     */
    public function getPieceCountLimit()
    {
        return $this->container['piece_count_limit'];
    }

    /**
     * Sets piece_count_limit
     *
     * @param int|null $piece_count_limit piece_count_limit
     *
     * @return self
     */
    public function setPieceCountLimit($piece_count_limit)
    {

        if (is_null($piece_count_limit)) {
            throw new \InvalidArgumentException('non-nullable piece_count_limit cannot be null');
        }

        $this->container['piece_count_limit'] = $piece_count_limit;

        return $this;
    }

    /**
     * Gets html
     *
     * @return string|null
     */
    public function getHtml()
    {
        return $this->container['html'];
    }

    /**
     * Sets html
     *
     * @param string|null $html html
     *
     * @return self
     */
    public function setHtml($html)
    {

        if (is_null($html)) {
            throw new \InvalidArgumentException('non-nullable html cannot be null');
        }

        $this->container['html'] = $html;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return (string)json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


