<?php
/**
 * ServicePointCapabilitiesModelAttributes
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Global Service Point Locator API
 *
 * Web service for getting DHL Service Points
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DHL\GSPL\Model;

/**
 * ServicePointCapabilitiesModelAttributes Class Doc Comment
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServicePointCapabilitiesModelAttributes
{
    public string $strParkingAvailable = 'parking_available';
    public string $strDisabledAccess = 'disabled_access';
    public string $strShipmentDropOff = 'shipment_drop_off';
    public string $strShipmentCollection = 'shipment_collection';
    public string $strInternationalShipping = 'international_shipping';
    public string $strDomesticShipping = 'domestic_shipping';
    public string $strAccountShippers = 'account_shippers';
    public string $strLabelPrinting = 'label_printing';
    public string $strInsurance = 'insurance';
    public string $strImportCharges = 'import_charges';
    public string $strPackaging = 'packaging';
    public string $strReceiverPaid = 'receiver_paid';
    public string $strVisaProgram = 'visa_program';
    public string $strPayWithCash = 'pay_with_cash';
    public string $strPayWithCreditCard = 'pay_with_credit_card';
    public string $strPayWithCheque = 'pay_with_cheque';
    public string $strPayWithMobile = 'pay_with_mobile';
    public string $strPayWithPayPal = 'pay_with_pay_pal';
    public string $strParkintTitle = 'parkint_title';
    public string $strDisabledAccessTitle = 'disabled_access_title';
    public string $strPieceWeightLimit = 'piece_weight_limit';
    public string $strPieceWeightLimitUnit = 'piece_weight_limit_unit';
    public string $strPieceDimensionsLimit = 'piece_dimensions_limit';
    public string $strPieceDimensionsLimitUnit = 'piece_dimensions_limit_unit';
    public string $strPieceCountLimit = 'piece_count_limit';
    public string $strHtml = 'html';
}

