<?php
/**
 * ServicePoint
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Global Service Point Locator API
 *
 * Web service for getting DHL Service Points
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DHL\GSPL\Model;

use \ArrayAccess;
use \DHL\GSPL\ObjectSerializer;

/**
 * ServicePoint Class Doc Comment
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ServicePoint implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * Return an object with the Model Fields
      *
      * @return ServicePointModelFields
      */
    public static function GetModelFields(): ServicePointModelFields
    {
        return new ServicePointModelFields();
    }

    /**
      * Return an object with the Model Attributes
      *
      * @return ServicePointModelAttributes
      */
    public static function GetModelAttributes(): ServicePointModelAttributes
    {
        return new ServicePointModelAttributes();
    }

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ServicePoint';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'facility_id' => 'string',
        'facility_type_code' => 'string',
        'service_area_code' => 'string',
        'service_point_name' => 'string',
        'service_point_name_formatted' => 'string',
        'local_name' => 'string',
        'service_point_type' => 'string',
        'address' => '\DHL\GSPL\Model\Address',
        'geo_location' => '\DHL\GSPL\Model\GeoLocation',
        'distance' => 'string',
        'opening_hours' => '\DHL\GSPL\Model\OpeningHours',
        'service_point_capabilities' => '\DHL\GSPL\Model\ServicePointCapabilities',
        'contact_details' => '\DHL\GSPL\Model\ContactDetails',
        'shipping_cut_off_time_html' => 'string',
        'distance_value' => 'string',
        'distance_metric' => 'float',
        'language' => '\DHL\GSPL\Model\Language',
        'shipment_limitations' => '\DHL\GSPL\Model\ShipmentLimitations',
        'shipment_limitations_by_piece' => '\DHL\GSPL\Model\ShipmentLimitationsByPiece',
        'charge_code' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'facility_id' => null,
        'facility_type_code' => null,
        'service_area_code' => null,
        'service_point_name' => null,
        'service_point_name_formatted' => null,
        'local_name' => null,
        'service_point_type' => null,
        'address' => null,
        'geo_location' => null,
        'distance' => null,
        'opening_hours' => null,
        'service_point_capabilities' => null,
        'contact_details' => null,
        'shipping_cut_off_time_html' => null,
        'distance_value' => null,
        'distance_metric' => null,
        'language' => null,
        'shipment_limitations' => null,
        'shipment_limitations_by_piece' => null,
        'charge_code' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'facility_id' => false,
		'facility_type_code' => false,
		'service_area_code' => false,
		'service_point_name' => false,
		'service_point_name_formatted' => false,
		'local_name' => false,
		'service_point_type' => false,
		'address' => false,
		'geo_location' => false,
		'distance' => false,
		'opening_hours' => false,
		'service_point_capabilities' => false,
		'contact_details' => false,
		'shipping_cut_off_time_html' => false,
		'distance_value' => false,
		'distance_metric' => false,
		'language' => false,
		'shipment_limitations' => false,
		'shipment_limitations_by_piece' => false,
		'charge_code' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'facility_id' => 'facilityId',
        'facility_type_code' => 'facilityTypeCode',
        'service_area_code' => 'serviceAreaCode',
        'service_point_name' => 'servicePointName',
        'service_point_name_formatted' => 'servicePointNameFormatted',
        'local_name' => 'localName',
        'service_point_type' => 'servicePointType',
        'address' => 'address',
        'geo_location' => 'geoLocation',
        'distance' => 'distance',
        'opening_hours' => 'openingHours',
        'service_point_capabilities' => 'servicePointCapabilities',
        'contact_details' => 'contactDetails',
        'shipping_cut_off_time_html' => 'shippingCutOffTimeHtml',
        'distance_value' => 'distanceValue',
        'distance_metric' => 'distanceMetric',
        'language' => 'language',
        'shipment_limitations' => 'shipmentLimitations',
        'shipment_limitations_by_piece' => 'shipmentLimitationsByPiece',
        'charge_code' => 'chargeCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'facility_id' => 'setFacilityId',
        'facility_type_code' => 'setFacilityTypeCode',
        'service_area_code' => 'setServiceAreaCode',
        'service_point_name' => 'setServicePointName',
        'service_point_name_formatted' => 'setServicePointNameFormatted',
        'local_name' => 'setLocalName',
        'service_point_type' => 'setServicePointType',
        'address' => 'setAddress',
        'geo_location' => 'setGeoLocation',
        'distance' => 'setDistance',
        'opening_hours' => 'setOpeningHours',
        'service_point_capabilities' => 'setServicePointCapabilities',
        'contact_details' => 'setContactDetails',
        'shipping_cut_off_time_html' => 'setShippingCutOffTimeHtml',
        'distance_value' => 'setDistanceValue',
        'distance_metric' => 'setDistanceMetric',
        'language' => 'setLanguage',
        'shipment_limitations' => 'setShipmentLimitations',
        'shipment_limitations_by_piece' => 'setShipmentLimitationsByPiece',
        'charge_code' => 'setChargeCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'facility_id' => 'getFacilityId',
        'facility_type_code' => 'getFacilityTypeCode',
        'service_area_code' => 'getServiceAreaCode',
        'service_point_name' => 'getServicePointName',
        'service_point_name_formatted' => 'getServicePointNameFormatted',
        'local_name' => 'getLocalName',
        'service_point_type' => 'getServicePointType',
        'address' => 'getAddress',
        'geo_location' => 'getGeoLocation',
        'distance' => 'getDistance',
        'opening_hours' => 'getOpeningHours',
        'service_point_capabilities' => 'getServicePointCapabilities',
        'contact_details' => 'getContactDetails',
        'shipping_cut_off_time_html' => 'getShippingCutOffTimeHtml',
        'distance_value' => 'getDistanceValue',
        'distance_metric' => 'getDistanceMetric',
        'language' => 'getLanguage',
        'shipment_limitations' => 'getShipmentLimitations',
        'shipment_limitations_by_piece' => 'getShipmentLimitationsByPiece',
        'charge_code' => 'getChargeCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('facility_id', $data ?? [], null);
        $this->setIfExists('facility_type_code', $data ?? [], null);
        $this->setIfExists('service_area_code', $data ?? [], null);
        $this->setIfExists('service_point_name', $data ?? [], null);
        $this->setIfExists('service_point_name_formatted', $data ?? [], null);
        $this->setIfExists('local_name', $data ?? [], null);
        $this->setIfExists('service_point_type', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('geo_location', $data ?? [], null);
        $this->setIfExists('distance', $data ?? [], null);
        $this->setIfExists('opening_hours', $data ?? [], null);
        $this->setIfExists('service_point_capabilities', $data ?? [], null);
        $this->setIfExists('contact_details', $data ?? [], null);
        $this->setIfExists('shipping_cut_off_time_html', $data ?? [], null);
        $this->setIfExists('distance_value', $data ?? [], null);
        $this->setIfExists('distance_metric', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('shipment_limitations', $data ?? [], null);
        $this->setIfExists('shipment_limitations_by_piece', $data ?? [], null);
        $this->setIfExists('charge_code', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets facility_id
     *
     * @return string|null
     */
    public function getFacilityId()
    {
        return $this->container['facility_id'];
    }

    /**
     * Sets facility_id
     *
     * @param string|null $facility_id facility_id
     *
     * @return self
     */
    public function setFacilityId($facility_id)
    {

        if (is_null($facility_id)) {
            throw new \InvalidArgumentException('non-nullable facility_id cannot be null');
        }

        $this->container['facility_id'] = $facility_id;

        return $this;
    }

    /**
     * Gets facility_type_code
     *
     * @return string|null
     */
    public function getFacilityTypeCode()
    {
        return $this->container['facility_type_code'];
    }

    /**
     * Sets facility_type_code
     *
     * @param string|null $facility_type_code facility_type_code
     *
     * @return self
     */
    public function setFacilityTypeCode($facility_type_code)
    {

        if (is_null($facility_type_code)) {
            throw new \InvalidArgumentException('non-nullable facility_type_code cannot be null');
        }

        $this->container['facility_type_code'] = $facility_type_code;

        return $this;
    }

    /**
     * Gets service_area_code
     *
     * @return string|null
     */
    public function getServiceAreaCode()
    {
        return $this->container['service_area_code'];
    }

    /**
     * Sets service_area_code
     *
     * @param string|null $service_area_code service_area_code
     *
     * @return self
     */
    public function setServiceAreaCode($service_area_code)
    {

        if (is_null($service_area_code)) {
            throw new \InvalidArgumentException('non-nullable service_area_code cannot be null');
        }

        $this->container['service_area_code'] = $service_area_code;

        return $this;
    }

    /**
     * Gets service_point_name
     *
     * @return string|null
     */
    public function getServicePointName()
    {
        return $this->container['service_point_name'];
    }

    /**
     * Sets service_point_name
     *
     * @param string|null $service_point_name service_point_name
     *
     * @return self
     */
    public function setServicePointName($service_point_name)
    {

        if (is_null($service_point_name)) {
            throw new \InvalidArgumentException('non-nullable service_point_name cannot be null');
        }

        $this->container['service_point_name'] = $service_point_name;

        return $this;
    }

    /**
     * Gets service_point_name_formatted
     *
     * @return string|null
     */
    public function getServicePointNameFormatted()
    {
        return $this->container['service_point_name_formatted'];
    }

    /**
     * Sets service_point_name_formatted
     *
     * @param string|null $service_point_name_formatted service_point_name_formatted
     *
     * @return self
     */
    public function setServicePointNameFormatted($service_point_name_formatted)
    {

        if (is_null($service_point_name_formatted)) {
            throw new \InvalidArgumentException('non-nullable service_point_name_formatted cannot be null');
        }

        $this->container['service_point_name_formatted'] = $service_point_name_formatted;

        return $this;
    }

    /**
     * Gets local_name
     *
     * @return string|null
     */
    public function getLocalName()
    {
        return $this->container['local_name'];
    }

    /**
     * Sets local_name
     *
     * @param string|null $local_name local_name
     *
     * @return self
     */
    public function setLocalName($local_name)
    {

        if (is_null($local_name)) {
            throw new \InvalidArgumentException('non-nullable local_name cannot be null');
        }

        $this->container['local_name'] = $local_name;

        return $this;
    }

    /**
     * Gets service_point_type
     *
     * @return string|null
     */
    public function getServicePointType()
    {
        return $this->container['service_point_type'];
    }

    /**
     * Sets service_point_type
     *
     * @param string|null $service_point_type service_point_type
     *
     * @return self
     */
    public function setServicePointType($service_point_type)
    {

        if (is_null($service_point_type)) {
            throw new \InvalidArgumentException('non-nullable service_point_type cannot be null');
        }

        $this->container['service_point_type'] = $service_point_type;

        return $this;
    }

    /**
     * Gets address
     *
     * @return \DHL\GSPL\Model\Address|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \DHL\GSPL\Model\Address|null $address address
     *
     * @return self
     */
    public function setAddress($address)
    {

        if (is_null($address)) {
            throw new \InvalidArgumentException('non-nullable address cannot be null');
        }

        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets geo_location
     *
     * @return \DHL\GSPL\Model\GeoLocation|null
     */
    public function getGeoLocation()
    {
        return $this->container['geo_location'];
    }

    /**
     * Sets geo_location
     *
     * @param \DHL\GSPL\Model\GeoLocation|null $geo_location geo_location
     *
     * @return self
     */
    public function setGeoLocation($geo_location)
    {

        if (is_null($geo_location)) {
            throw new \InvalidArgumentException('non-nullable geo_location cannot be null');
        }

        $this->container['geo_location'] = $geo_location;

        return $this;
    }

    /**
     * Gets distance
     *
     * @return string|null
     */
    public function getDistance()
    {
        return $this->container['distance'];
    }

    /**
     * Sets distance
     *
     * @param string|null $distance distance
     *
     * @return self
     */
    public function setDistance($distance)
    {

        if (is_null($distance)) {
            throw new \InvalidArgumentException('non-nullable distance cannot be null');
        }

        $this->container['distance'] = $distance;

        return $this;
    }

    /**
     * Gets opening_hours
     *
     * @return \DHL\GSPL\Model\OpeningHours|null
     */
    public function getOpeningHours()
    {
        return $this->container['opening_hours'];
    }

    /**
     * Sets opening_hours
     *
     * @param \DHL\GSPL\Model\OpeningHours|null $opening_hours opening_hours
     *
     * @return self
     */
    public function setOpeningHours($opening_hours)
    {

        if (is_null($opening_hours)) {
            throw new \InvalidArgumentException('non-nullable opening_hours cannot be null');
        }

        $this->container['opening_hours'] = $opening_hours;

        return $this;
    }

    /**
     * Gets service_point_capabilities
     *
     * @return \DHL\GSPL\Model\ServicePointCapabilities|null
     */
    public function getServicePointCapabilities()
    {
        return $this->container['service_point_capabilities'];
    }

    /**
     * Sets service_point_capabilities
     *
     * @param \DHL\GSPL\Model\ServicePointCapabilities|null $service_point_capabilities service_point_capabilities
     *
     * @return self
     */
    public function setServicePointCapabilities($service_point_capabilities)
    {

        if (is_null($service_point_capabilities)) {
            throw new \InvalidArgumentException('non-nullable service_point_capabilities cannot be null');
        }

        $this->container['service_point_capabilities'] = $service_point_capabilities;

        return $this;
    }

    /**
     * Gets contact_details
     *
     * @return \DHL\GSPL\Model\ContactDetails|null
     */
    public function getContactDetails()
    {
        return $this->container['contact_details'];
    }

    /**
     * Sets contact_details
     *
     * @param \DHL\GSPL\Model\ContactDetails|null $contact_details contact_details
     *
     * @return self
     */
    public function setContactDetails($contact_details)
    {

        if (is_null($contact_details)) {
            throw new \InvalidArgumentException('non-nullable contact_details cannot be null');
        }

        $this->container['contact_details'] = $contact_details;

        return $this;
    }

    /**
     * Gets shipping_cut_off_time_html
     *
     * @return string|null
     */
    public function getShippingCutOffTimeHtml()
    {
        return $this->container['shipping_cut_off_time_html'];
    }

    /**
     * Sets shipping_cut_off_time_html
     *
     * @param string|null $shipping_cut_off_time_html shipping_cut_off_time_html
     *
     * @return self
     */
    public function setShippingCutOffTimeHtml($shipping_cut_off_time_html)
    {

        if (is_null($shipping_cut_off_time_html)) {
            throw new \InvalidArgumentException('non-nullable shipping_cut_off_time_html cannot be null');
        }

        $this->container['shipping_cut_off_time_html'] = $shipping_cut_off_time_html;

        return $this;
    }

    /**
     * Gets distance_value
     *
     * @return string|null
     */
    public function getDistanceValue()
    {
        return $this->container['distance_value'];
    }

    /**
     * Sets distance_value
     *
     * @param string|null $distance_value distance_value
     *
     * @return self
     */
    public function setDistanceValue($distance_value)
    {

        if (is_null($distance_value)) {
            throw new \InvalidArgumentException('non-nullable distance_value cannot be null');
        }

        $this->container['distance_value'] = $distance_value;

        return $this;
    }

    /**
     * Gets distance_metric
     *
     * @return float|null
     */
    public function getDistanceMetric()
    {
        return $this->container['distance_metric'];
    }

    /**
     * Sets distance_metric
     *
     * @param float|null $distance_metric distance_metric
     *
     * @return self
     */
    public function setDistanceMetric($distance_metric)
    {

        if (is_null($distance_metric)) {
            throw new \InvalidArgumentException('non-nullable distance_metric cannot be null');
        }

        $this->container['distance_metric'] = $distance_metric;

        return $this;
    }

    /**
     * Gets language
     *
     * @return \DHL\GSPL\Model\Language|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param \DHL\GSPL\Model\Language|null $language language
     *
     * @return self
     */
    public function setLanguage($language)
    {

        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }

        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets shipment_limitations
     *
     * @return \DHL\GSPL\Model\ShipmentLimitations|null
     */
    public function getShipmentLimitations()
    {
        return $this->container['shipment_limitations'];
    }

    /**
     * Sets shipment_limitations
     *
     * @param \DHL\GSPL\Model\ShipmentLimitations|null $shipment_limitations shipment_limitations
     *
     * @return self
     */
    public function setShipmentLimitations($shipment_limitations)
    {

        if (is_null($shipment_limitations)) {
            throw new \InvalidArgumentException('non-nullable shipment_limitations cannot be null');
        }

        $this->container['shipment_limitations'] = $shipment_limitations;

        return $this;
    }

    /**
     * Gets shipment_limitations_by_piece
     *
     * @return \DHL\GSPL\Model\ShipmentLimitationsByPiece|null
     */
    public function getShipmentLimitationsByPiece()
    {
        return $this->container['shipment_limitations_by_piece'];
    }

    /**
     * Sets shipment_limitations_by_piece
     *
     * @param \DHL\GSPL\Model\ShipmentLimitationsByPiece|null $shipment_limitations_by_piece shipment_limitations_by_piece
     *
     * @return self
     */
    public function setShipmentLimitationsByPiece($shipment_limitations_by_piece)
    {

        if (is_null($shipment_limitations_by_piece)) {
            throw new \InvalidArgumentException('non-nullable shipment_limitations_by_piece cannot be null');
        }

        $this->container['shipment_limitations_by_piece'] = $shipment_limitations_by_piece;

        return $this;
    }

    /**
     * Gets charge_code
     *
     * @return string|null
     */
    public function getChargeCode()
    {
        return $this->container['charge_code'];
    }

    /**
     * Sets charge_code
     *
     * @param string|null $charge_code charge_code
     *
     * @return self
     */
    public function setChargeCode($charge_code)
    {

        if (is_null($charge_code)) {
            throw new \InvalidArgumentException('non-nullable charge_code cannot be null');
        }

        $this->container['charge_code'] = $charge_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return (string)json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


