<?php
/**
 * ServicePointCapabilitiesModelFields
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Global Service Point Locator API
 *
 * Web service for getting DHL Service Points
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DHL\GSPL\Model;

/**
 * ServicePointCapabilitiesModelFields Class Doc Comment
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServicePointCapabilitiesModelFields
{
    public string $strParkingAvailable = 'parkingAvailable';
    public string $strDisabledAccess = 'disabledAccess';
    public string $strShipmentDropOff = 'shipmentDropOff';
    public string $strShipmentCollection = 'shipmentCollection';
    public string $strInternationalShipping = 'internationalShipping';
    public string $strDomesticShipping = 'domesticShipping';
    public string $strAccountShippers = 'accountShippers';
    public string $strLabelPrinting = 'labelPrinting';
    public string $strInsurance = 'insurance';
    public string $strImportCharges = 'importCharges';
    public string $strPackaging = 'packaging';
    public string $strReceiverPaid = 'receiverPaid';
    public string $strVisaProgram = 'visaProgram';
    public string $strPayWithCash = 'payWithCash';
    public string $strPayWithCreditCard = 'payWithCreditCard';
    public string $strPayWithCheque = 'payWithCheque';
    public string $strPayWithMobile = 'payWithMobile';
    public string $strPayWithPayPal = 'payWithPayPal';
    public string $strParkintTitle = 'parkintTitle';
    public string $strDisabledAccessTitle = 'disabledAccessTitle';
    public string $strPieceWeightLimit = 'pieceWeightLimit';
    public string $strPieceWeightLimitUnit = 'pieceWeightLimitUnit';
    public string $strPieceDimensionsLimit = 'pieceDimensionsLimit';
    public string $strPieceDimensionsLimitUnit = 'pieceDimensionsLimitUnit';
    public string $strPieceCountLimit = 'pieceCountLimit';
    public string $strHtml = 'html';
}

