<?php
/**
 * LanguageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spy\Package\SpyClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Global Service Point Locator API
 *
 * Web service for getting DHL Service Points
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Spy\Package\SpyClient;

/**
 * LanguageTest Class Doc Comment
 *
 * @category    Class
 * @description Language
 * @package     Spy\Package\SpyClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LanguageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Language"
     */
    public function testLanguage()
    {
    }

    /**
     * Test attribute "language_code"
     */
    public function testPropertyLanguageCode()
    {
    }

    /**
     * Test attribute "language_script_code"
     */
    public function testPropertyLanguageScriptCode()
    {
    }

    /**
     * Test attribute "language_country_code"
     */
    public function testPropertyLanguageCountryCode()
    {
    }

    /**
     * Test attribute "language_ok"
     */
    public function testPropertyLanguageOk()
    {
    }
}
