<?php
/**
 * MapTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spy\Package\SpyClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Global Service Point Locator API
 *
 * Web service for getting DHL Service Points
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Spy\Package\SpyClient;

/**
 * MapTest Class Doc Comment
 *
 * @category    Class
 * @description Map
 * @package     Spy\Package\SpyClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MapTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Map"
     */
    public function testMap()
    {
    }

    /**
     * Test attribute "sp_detail"
     */
    public function testPropertySpDetail()
    {
    }

    /**
     * Test attribute "aditional_info"
     */
    public function testPropertyAditionalInfo()
    {
    }

    /**
     * Test attribute "services"
     */
    public function testPropertyServices()
    {
    }

    /**
     * Test attribute "opening_hours"
     */
    public function testPropertyOpeningHours()
    {
    }

    /**
     * Test attribute "limitation_by_shipment"
     */
    public function testPropertyLimitationByShipment()
    {
    }

    /**
     * Test attribute "holiday_hours"
     */
    public function testPropertyHolidayHours()
    {
    }

    /**
     * Test attribute "limitation"
     */
    public function testPropertyLimitation()
    {
    }

    /**
     * Test attribute "limitation_by_piece"
     */
    public function testPropertyLimitationByPiece()
    {
    }

    /**
     * Test attribute "print"
     */
    public function testPropertyPrint()
    {
    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {
    }

    /**
     * Test attribute "route"
     */
    public function testPropertyRoute()
    {
    }

    /**
     * Test attribute "contact_details"
     */
    public function testPropertyContactDetails()
    {
    }

    /**
     * Test attribute "found"
     */
    public function testPropertyFound()
    {
    }
}
