<?php
/**
 * ServicePointCapabilitiesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Global Service Point Locator API
 *
 * Web service for getting DHL Service Points
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DHL\GSPL;

/**
 * ServicePointCapabilitiesTest Class Doc Comment
 *
 * @category    Class
 * @description ServicePointCapabilities
 * @package     DHL\GSPL
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ServicePointCapabilitiesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ServicePointCapabilities"
     */
    public function testServicePointCapabilities()
    {
    }

    /**
     * Test attribute "parking_available"
     */
    public function testPropertyParkingAvailable()
    {
    }

    /**
     * Test attribute "disabled_access"
     */
    public function testPropertyDisabledAccess()
    {
    }

    /**
     * Test attribute "shipment_drop_off"
     */
    public function testPropertyShipmentDropOff()
    {
    }

    /**
     * Test attribute "shipment_collection"
     */
    public function testPropertyShipmentCollection()
    {
    }

    /**
     * Test attribute "international_shipping"
     */
    public function testPropertyInternationalShipping()
    {
    }

    /**
     * Test attribute "domestic_shipping"
     */
    public function testPropertyDomesticShipping()
    {
    }

    /**
     * Test attribute "account_shippers"
     */
    public function testPropertyAccountShippers()
    {
    }

    /**
     * Test attribute "label_printing"
     */
    public function testPropertyLabelPrinting()
    {
    }

    /**
     * Test attribute "insurance"
     */
    public function testPropertyInsurance()
    {
    }

    /**
     * Test attribute "import_charges"
     */
    public function testPropertyImportCharges()
    {
    }

    /**
     * Test attribute "packaging"
     */
    public function testPropertyPackaging()
    {
    }

    /**
     * Test attribute "receiver_paid"
     */
    public function testPropertyReceiverPaid()
    {
    }

    /**
     * Test attribute "visa_program"
     */
    public function testPropertyVisaProgram()
    {
    }

    /**
     * Test attribute "pay_with_cash"
     */
    public function testPropertyPayWithCash()
    {
    }

    /**
     * Test attribute "pay_with_credit_card"
     */
    public function testPropertyPayWithCreditCard()
    {
    }

    /**
     * Test attribute "pay_with_cheque"
     */
    public function testPropertyPayWithCheque()
    {
    }

    /**
     * Test attribute "pay_with_mobile"
     */
    public function testPropertyPayWithMobile()
    {
    }

    /**
     * Test attribute "pay_with_pay_pal"
     */
    public function testPropertyPayWithPayPal()
    {
    }

    /**
     * Test attribute "parkint_title"
     */
    public function testPropertyParkintTitle()
    {
    }

    /**
     * Test attribute "disabled_access_title"
     */
    public function testPropertyDisabledAccessTitle()
    {
    }

    /**
     * Test attribute "piece_weight_limit"
     */
    public function testPropertyPieceWeightLimit()
    {
    }

    /**
     * Test attribute "piece_weight_limit_unit"
     */
    public function testPropertyPieceWeightLimitUnit()
    {
    }

    /**
     * Test attribute "piece_dimensions_limit"
     */
    public function testPropertyPieceDimensionsLimit()
    {
    }

    /**
     * Test attribute "piece_dimensions_limit_unit"
     */
    public function testPropertyPieceDimensionsLimitUnit()
    {
    }

    /**
     * Test attribute "piece_count_limit"
     */
    public function testPropertyPieceCountLimit()
    {
    }

    /**
     * Test attribute "html"
     */
    public function testPropertyHtml()
    {
    }
}
