<?php
/**
 * ShipmentLimitationsByPieceTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DHL\GSPL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Global Service Point Locator API
 *
 * Web service for getting DHL Service Points
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DHL\GSPL\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ShipmentLimitationsByPieceTest Class Doc Comment
 *
 * @category    Class
 * @description ShipmentLimitationsByPiece
 * @package     DHL\GSPL
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShipmentLimitationsByPieceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShipmentLimitationsByPiece"
     */
    public function testShipmentLimitationsByPiece()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "piece_size_limit1"
     */
    public function testPropertyPieceSizeLimit1()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "piece_size_limit2"
     */
    public function testPropertyPieceSizeLimit2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "piece_size_limit3"
     */
    public function testPropertyPieceSizeLimit3()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "max_piece_weight"
     */
    public function testPropertyMaxPieceWeight()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "html"
     */
    public function testPropertyHtml()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
