<?php
/**
 * ShipmentLimitationsByPieceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spy\Package\SpyClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Global Service Point Locator API
 *
 * Web service for getting DHL Service Points
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@spysystem.dk
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Spy\Package\SpyClient;

/**
 * ShipmentLimitationsByPieceTest Class Doc Comment
 *
 * @category    Class
 * @description ShipmentLimitationsByPiece
 * @package     Spy\Package\SpyClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShipmentLimitationsByPieceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShipmentLimitationsByPiece"
     */
    public function testShipmentLimitationsByPiece()
    {
    }

    /**
     * Test attribute "piece_size_limit1"
     */
    public function testPropertyPieceSizeLimit1()
    {
    }

    /**
     * Test attribute "piece_size_limit2"
     */
    public function testPropertyPieceSizeLimit2()
    {
    }

    /**
     * Test attribute "piece_size_limit3"
     */
    public function testPropertyPieceSizeLimit3()
    {
    }

    /**
     * Test attribute "max_piece_weight"
     */
    public function testPropertyMaxPieceWeight()
    {
    }

    /**
     * Test attribute "html"
     */
    public function testPropertyHtml()
    {
    }
}
